apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-multiplayer-deployment
  labels:
    app: scalable-multiplayer
  namespace: multiplayer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scalable-multiplayer
  template:
    metadata:
      labels:
        app: scalable-multiplayer
    spec:
      containers:
      - name: app
        image: admin3005/scalable-multiplayer:latest
        ports:
          - containerPort: 8080
        env:
          - name: REDIS_URL
            value: redis://redis-service:6379
        readinessProbe:     
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
        livenessProbe:     
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"