services:
  app:
    image: admin3005/scalable-multiplayer:latest
    container_name: scalable-multiplayer
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    restart: always
    networks:
      - custom-network
  
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge

volumes:
  redis_data: